SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (1, N'Intel Core i5-10600KF', N'CPU', CAST(6284.00 AS Decimal(18, 2)), N'/images\Products\Intel Core i5-10600KF.jfif', N'Intel Core i5-10600KF', N'Společnost Intel představuje 10. generaci procesorů pro stolní počítač s označením Comet Lake. Ať už jste hráč, hledající fantastický herní zážitek s dostatkem výkonu pro hladké streamování a nepřerušované nahrávání nejdůležitějších momentů nebo jste tvůrce obsahu, který chce strávit méně času čekáním při tvoření a sdílení, tato 10. generace procesorů Intel je na to připravena. Verze KF nabízí odemčený násobič a není vybavena grafickým jádrem.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (2, N'Intel Core i3-10100F', N'CPU', CAST(2436.00 AS Decimal(18, 2)), N'/images\Products\Core i3-10100F.jfif', N'Intel Core i3-10100F', N'Společnost Intel představuje 10. generaci procesorů pro stolní počítač s označením Comet Lake. Ať už jste hráč, hledající fantastický herní zážitek s dostatkem výkonu pro hladké streamování a nepřerušované nahrávání nejdůležitějších momentů nebo jste tvůrce obsahu, který chce strávit méně času čekáním při tvoření a sdílení, tato 10. generace procesorů Intel je na to připravena. Verze F není vybavena grafickým jádrem.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (3, N'Intel Core i9-10900X', N'CPU', CAST(15806.00 AS Decimal(18, 2)), N'/images\Products\Intel Core i9-10900X.jfif', N'Intel Core i9-10900X', N'Intel Core i9-10900X
Ať už pracujete na nejnovějším filmu či další epizodě YouTube série, odemčené procesory série Intel Core X jsou vytvořeny pro uzpůsobení výkonu vaším potřebám: s až 18 jádry a vylepšenou technologií Intel Turbo Boost Max 3.0, která přesměruje vaše nejdůležitější úkony na 4 nejrychlejší jádra.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (4, N'AMD Ryzen 5 5600X', N'CPU', CAST(7990.00 AS Decimal(18, 2)), N'/images\Products\AMD Ryzen 5 5600X.jfif', N'AMD Ryzen 5 5600X', N'Když máte světově nejpokročilejší architekturu procesoru pro hráče a tvůrce obsahu, jsou možnosti nekonečné. Ať už hrajete nejnovější hry, navrhujete nejmodernější mrakodrap, či zpracováváte velké množství dat, potřebujete výkonný procesor, který to vše zvládne. AMD Ryzen 5000 série stolních procesorů nastavuje novou laťku pro hráče a tvůrce obsahu.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (5, N'AMD Ryzen 7 5800X', N'CPU', CAST(12290.00 AS Decimal(18, 2)), N'/images\Products\AMD Ryzen 7 5800X.jfif', N'AMD Ryzen 7 5800X', N'Když máte světově nejpokročilejší architekturu procesoru pro hráče a tvůrce obsahu, jsou možnosti nekonečné. Ať už hrajete nejnovější hry, navrhujete nejmodernější mrakodrap, či zpracováváte velké množství dat, potřebujete výkonný procesor, který to vše zvládne. AMD Ryzen 5000 série stolních procesorů nastavuje novou laťku pro hráče a tvůrce obsahu.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (6, N'AMD Ryzen 9 5950X', N'CPU', CAST(20997.00 AS Decimal(18, 2)), N'/images\Products\AMD Ryzen 9 5950X.jfif', N'AMD Ryzen 9 5950X', N'Ryzen 9 5950X
Když máte světově nejpokročilejší architekturu procesoru pro hráče a tvůrce obsahu, jsou možnosti nekonečné. Ať už hrajete nejnovější hry, navrhujete nejmodernější mrakodrap, či zpracováváte velké množství dat, potřebujete výkonný procesor, který to vše zvládne. AMD Ryzen 5000 série stolních procesorů nastavuje novou laťku pro hráče a tvůrce obsahu.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (7, N'GIGABYTE GeForce RTX 3090', N'GPU', CAST(46990.00 AS Decimal(18, 2)), N'/images\Products\GIGABYTE GeForce RTX 3090.jfif', N'GIGABYTE GeForce RTX 3090', N'Společnost Gigabyte přináší na trh svou extrémně výkonnou herní grafickou kartu ze série Turbo. Grafické karty GeForce RTX řady 30 přinášejí špičkový výkon pro hráče i tvůrce. Pohání je architektura Ampere – 2. generace architektury NVIDIA RTX – s novými jádry RT, jádry Tensor a multiprocesory pro streamování, která poskytuje nejrealističtější ray-tracovanou grafiku a špičkové funkce umělé inteligence. Tato varianta poskytuje 24 GB GDDR6X paměti s rychlostí 19,5 Gb/s.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (8, N'ASRock Radeon RX 6900 XT', N'GPU', CAST(27900.00 AS Decimal(18, 2)), N'/images\Products\ASRock Radeon RX 6900 XT.jfif', N'ASRock Radeon RX 6900 XT', N'ASRock Radeon RX 6900 XT 16G
AMD Radeon RX 6900 XT grafická karta, poháněná AMD RDNA 2 architekturou, poskytuje 80 výkonných, posílených výpočetních jednotek, 128 MB zcela nové AMD Infinity Cache a 16 GB dedikované GDDR6 paměti. Je vytvořena pro dodání ultra vysokých snímkových frekvencí a a 4K hraní.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (9, N'PALiT GeForce RTX 3060Ti', N'GPU', CAST(11990.00 AS Decimal(18, 2)), N'/images\Products\PALiT GeForce RTX 3060Ti.jfif', N'PALiT GeForce RTX 3060Ti', N'PALiT GeForce RTX 3060Ti GamingPro
Společnost PALiT přináší na trh svou vysoce výkonnou herní grafickou kartu ze série GamingPro. Grafické karty GeForce RTX řady 30 přinášejí špičkový výkon pro hráče i tvůrce. Pohání je architektura Ampere – 2. generace architektury NVIDIA RTX – s novými jádry RT, jádry Tensor a multiprocesory pro streamování, která poskytuje nejrealističtější ray-tracovanou grafiku a špičkové funkce umělé inteligence. Tato varianta poskytuje 8 GB GDDR6 paměti s rychlostí 14 Gb/s.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (10, N'DDR4 3600 CL20 2x8GB', N'Memory', CAST(2339.00 AS Decimal(18, 2)), N'/images\Products\DDR4 3600 CL20.jfif', N'DDR4 3600 CL20', N'Patriot Viper Steel RGB
Paměti Viper Steel RGB byly vytvořeny a sestaveny pro extrémní výkon a doplněny o dech-beroucí nastavitelné RGB osvětlení, aby perfektně zapadly do vaší sestavy. Součástí je také velmi kvalitní hliníkový chladič, který modulům dodává elegantní a stylový vzhled.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (11, N'DDR4 3200 CL16 2x16 GB', N'Memory', CAST(3501.00 AS Decimal(18, 2)), N'/images\Products\DDR4 3200 CL16.jfif', N'DDR4 3200 CL16', N'Kingston HyperX Fury
Firma Kingston vždy patřila a stále patří mezi přední výrobce a dodavatele paměťových modulů. Díky jejich vysoké kvalitě a spolehlivosti je ve svých modelových řadách používá i mnoho známých výrobců počítačů a jsou používány při testování nových základních desek, grafických karet apod. Paměťové moduly ze série HyperX Fury jsou dalším přírůstek do produktové řady DDR4 pamětí HyperX, nyní vybavené')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (12, N'DDR4 3200 CL16 1x8GB', N'Memory', CAST(1099.00 AS Decimal(18, 2)), N'/images\Products\DDR4 3200 CL16_8.jfif', N'DDR4 3200 CL16 1x8', N'ADATA XPG SPECTRIX D60G
Paměti XPG SPECTRIX D60G DDR4 jsou vybaveny jedinečnými dvěma RGB světelnými pásy, které představují největší RGB plochu na paměťovém modulu! Podporují profily Intel XMP 2.0 pro snadné přetaktování.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (13, N'GIGABYTE P650B - 650W', N'Power Supply', CAST(2448.00 AS Decimal(18, 2)), N'/images\Products\GIGABYTE P650B - 650W.jfif', N'GIGABYTE P650B - 650W', N'Záruka dobrého počítačového zdroje: Gigabyte P650B
Značka Gigabyte je počítačovým nadšencům velmi dobře známá. Etablovala se jako garant spolehlivých komponent, které nabízejí příkladný výkon a mohou se chlubit i velmi dobrou výdrží a nízkou poruchovostí. Právě z této kategorie výrobků je moderní počítačový zdroj, který disponuje celou řadou elektrických fines a úporných řešení.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (14, N'Seasonic Focus (GX-850) - 850W', N'Power Supply', CAST(3699.00 AS Decimal(18, 2)), N'/images\Products\Seasonic Focus (GX-850) - 850W.jfif', N'Seasonic Focus (GX-850) ', N'Seasonic Focus GX
Zdroje Focus GX jsou nástupcem Seasonic Focus Plus série zdrojů, které se v době vydání staly okamžitým hitem. Inženýři Seasonic v této nové verzi provedli řadu vylepšení, jako odebrání kondenzátorů z kabelů.Kromě malé změny v pojmenování série, bylo také změněno tělo a balení, aby odpovídalo konceptu OneSeasonic iniciativy, která zjednodušuje a sjednocuje pojmenování produktů pro snadnou identifikaci jeho funkcí. G - 80 Plus Gold certifikace, X - plně modulární design.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (15, N'SilentiumPC Elementum E2', N'Power Supply', CAST(899.00 AS Decimal(18, 2)), N'/images\Products\SilentiumPC Elementum E2.jfif', N'SilentiumPC Elementum E2', N'SilentiumPC Elementum E2
Společnost SilentiumPC se zabývá tvorbou chladičů, PC skříní, napájecích zdrojů a různých příslušenství. Ta vám nyní přináší svůj zdroj nesoucí název Elementum E2.

Zdroj počítači poskytuje stálý výkon až 350 W. Zdroj je vybaven tichým ventilátorem o velikosti 120 mm s automatickou regulací otáček. Nabízí ochranu proti přepětí, podpětí a zkratu. Má certifikaci 80Plus, která garantuje minimální účinnost 82%.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (16, N'ASUS TUF GAMING B550-PLUS', N'Motherboard', CAST(3489.00 AS Decimal(18, 2)), N'/images\Products\ASUS TUF GAMING B550-PLUS.jfif', N'ASUS TUF GAMING B550-PLUS', N'TUF Gaming B550-Plus destiluje důležité prvky nejnovější AMD platformy a kombinuje je s herními funkcemi a prokázanou výdrží. Vytvořena s komponenty armádní kvality, vylepšeným napájecím řešením a srozumitelnou sadou chladících funkcí, tato základní deska přináší skálopevný výkon s nepolevující herní stabilitou.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (17, N'ASUS PRIME Z490-P', N'Motherboard', CAST(3199.00 AS Decimal(18, 2)), N'/images\Products\ASUS PRIME Z490-P.jfif', N'ASUS PRIME Z490-P', N'ASUS Prime série je expertně sestrojena pro využití plného potenciálu 10. generace Intel Core procesorů. Vybaveny robustním designem napájení, srozumitelnými řešeními chlazení a inteligentními možnostmi tuningu, základní desky série Z490 poskytují běžným uživatelům a stavitelům sestav řadu možností vylepšení výkonu, skrze intuitivní funkce softwaru a firmwaru.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (18, N'MSI B450M-A PRO MAX', N'Motherboard', CAST(1492.00 AS Decimal(18, 2)), N'/images\Products\MSI B450M-A PRO MAX.jfif', N'MSI B450M-A PRO MAX', N'MSI B450M-A PRO MAX
Kvalita na kterou se můžete spolehnout a chytré firemní řešení jsou klíčové aspekty MSI PRO série základních desek. Vytvořeny pro uspokojení i těch nejnáročnějších profesionálů – tyto desky se hodí do jakéhokoliv počítače. Usnadní vám život a podpoří vaše podnikání se super stabilním, spolehlivým a dlouhotrvajícím výkonem.')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (19, N'Kingston Now A400, 2,5" - 480GB', N'Storage', CAST(1375.00 AS Decimal(18, 2)), N'/images\Products\Kingston Now A400.jfif', N'Kingston Now A400', N'SSD jednotka značky Kingston dramaticky vylepšuje odezvu vašeho počítačového systému - zrychluje jeho start, nahrávání aplikací a přenosovou rychlost dat. Je poháněn nejmodernějším řadičem pro čtení a zápis datových balíků. SSD je díky tomu rychlejší až 10x ve srovnání s tradičním harddiskem. To vše se příznivě projevuje také na příkladném multitaskingu, který nabízí celý systém. ')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (20, N'Kingston A2000, M.2 - 1TB', N'Storage', CAST(2799.00 AS Decimal(18, 2)), N'/images\Products\Kingston A2000, M.2 - 1TB.jfif', N'Kingston A2000, M.2 - 1TB', N'SSD disk A2000 NVMe PCIe značky Kingston představuje cenově dostupné řešení s působivým výkonem. S vynikajícími rychlostmi čtení/zápisu disk A2000 nabízí 3x vyšší výkon než SSD disk SATA, a to díky kratší době načítání, menší spotřebě energie a menšímu zahřívání. SSD disk A2000 je určen pro uživatele na základní úrovni, výrobce účelových systémů, výrobce vlastních systémů a pro ty, kteří chtějí zvýšit výkon svého PC. Jednostranná tenká konstrukce M.2 umožňuje disku A2000 pracovat na plný výkon v ultrabooku i v PC systému v malém provedení (SFF PC).')
INSERT INTO [dbo].[Product] ([ID], [Name], [Category], [Price], [ImageSrc], [ImageAlt], [DetailProduktu]) VALUES (21, N'Seagate BarraCuda, 3,5" - 2TB', N'Storage', CAST(1549.00 AS Decimal(18, 2)), N'/images\Products\Seagate BarraCuda.jfif', N'Seagate BarraCuda', N'Seagate BarraCuda
Získejte co možná nejvíce ze svého úložiště s pevnými disky BarraCuda. Od počítačů plných fotografií a vzpomínek po herní PC, které vyžadují více prostoru pro hraní, BarraCuda poroste s vámi.')
SET IDENTITY_INSERT [dbo].[Product] OFF
